apiVersion: v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: chat-app
  spec:
  replicas: 3 
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      name: backend-pod
      namespace: chat-app
      labels:
        app: backend
    spec:
     containers:
      - name: backend-container
        image: tryhard231/chat-app-backend:v1
        ports:
        - containerPort: 5001
        env:
        - name: NODE_ENV
          value: "production"
